api:
  type: opnsense
  key: ""
  secret: ""

ifaces:
  eth4:
    - name: gw_main
      name_selector: WAN_DHCP6
      max_rtt: 300ms
      keep_for: 100s
      min_ttl: 2
      ips:
        - '::'
        - 'ffff::'
        - '2001:4860:4860::1888'
        - '2620:fe::9'
        # - '2001:4860:4860::8888'

    # - name: gw_main_v4
    #   name_selector: WAN_DHCP
    #   max_rtt: 100ms
    #   keep_for: 30s
    #   min_ttl: 3
    #   ips:
    #     - '1.1.1.0'
    #     # - '1.1.1.1'
